services: []
cronJobs:
    - name: supabase-storage-backup
      schedule: '0 5 * * *' # 5h da manhã todos os dias (UTC)
      command: 'npm install && node backup.js'
      envVars:
          - key: SUPABASE_URL
            sync: false
          - key: SUPABASE_SERVICE_ROLE_KEY
            sync: false
          - key: BUCKET_NAME
            sync: false
          - key: EMAIL_USER
            sync: false
          - key: EMAIL_PASS
            sync: false
          - key: EMAIL_TO
            sync: false
          - key: GOOGLE_DRIVE_FOLDER_ID
            sync: false
